changelog:
  exclude:
    labels:
      - ignore-for-release
  categories:
    - title: "🚀 New Features"
      labels:
        - feature
    - title: "✨ Enhancements"
      labels:
        - enhancement
    - title: "🐛 Bug Fixes"
      labels:
        - fix
    - title: "🔒 Security"
      labels:
        - security
    - title: "📖 Documentation"
      labels:
        - docs
    - title: "♻️ Refactoring"
      labels:
        - refactor
    - title: "🧪 Tests"
      labels:
        - test
    - title: "🗂 Specifications"
      labels:
        - spec
        - spec-archive
    - title: "🔧 Chores"
      labels:
        - chore
    - title: "🗒 Other Changes"
      labels:
        - "*"
