name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest # self-hosted-cpu
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v5
        with:
          go-version: '1.25.0'

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest
          install-mode: goinstall
          working-directory: src
          args: --new-from-rev=origin/main --timeout=5m --config .golangci.yml

  test:
    name: Test
    runs-on: ubuntu-latest # self-hosted-cpu
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: src/go.mod

      - name: Run tests
        working-directory: src
        run: make test
